fix typo

diff --git a/src/init_lynxbot b/src/init_lynxbot
--- a/src/init_lynxbot
+++ b/src/init_lynxbot
@@ -15,34 +15,34 @@ Connect to the first lynxbot.sh available.
 echo: nothing
 return 9 if fail, 0 if success."
 function LB_startlynxbot {
-    LynxPid=0
-    # search for a lynx to bot
-    for fifo in /tmp/lynx_cmd_input.* ; do 
-        if [ -p "$fifo" -a -p "${fifo/cmd_input/output}" -a ! -f "/tmp/current_bot.${fifo##*.}" ] ; then
-            export LynxBotPid=$$
-            export LynxPid=${fifo#*.}
-	    echo -e "LynxBotPid=$LynxBotPid" > "/tmp/current_bot.$LynxPid" || return 1
-            break;
-        fi
-    done
-    if ! ((LynxPid)) ; then
-        echo "${0##*/}: error: No lynx available to command" >&2
-        return 9
-    fi
-    
-    # stuff to avoid synchonisation problems
-    echo -n "0 _NULL_" > /tmp/current_link.$LynxBotPid || return 1
-    echo -n "0 _NULL_" > /tmp/current_linktype.$LynxBotPid || return 1
-    nbla_=1
+	LynxPid=0
+	# search for a lynx to bot
+	for fifo in /tmp/lynx_cmd_input.* ; do 
+		if [ -p "$fifo" -a -p "${fifo/cmd_input/output}" -a ! -f "/tmp/current_bot.${fifo##*.}" ] ; then
+			export LynxBotPid=$$
+			export LynxPid=${fifo#*.}
+		echo -e "LynxBotPid=$LynxBotPid" > "/tmp/current_bot.$LynxPid" || return 1
+			break;
+		fi
+	done
+	if ! ((LynxPid)) ; then
+		echo "${0##*/}: error: No lynx available to command" >&2
+		return 9
+	fi
+	
+	# stuff to avoid synchonisation problems
+	echo -n "0 _NULL_" > /tmp/current_link.$LynxBotPid || return 1
+	echo -n "0 _NULL_" > /tmp/current_linktype.$LynxBotPid || return 1
+	nbla_=1
 
-    # Start the lynx link and linktype extractor
-    "$LynxBotBin"/extractlastlinkfromlynx /tmp/current_link.$LynxBotPid /tmp/current_linktype.$LynxBotPid /tmp/current_error.$LynxBotPid < "/tmp/lynx_output.$LynxPid" &
-    
-    # open the input fifo on fd 3
-    exec 3<> "/tmp/lynx_cmd_input.$LynxPid"
+	# Start the lynx link and linktype extractor
+	"$LynxBotBin"/extractlastlinkfromlynx /tmp/current_link.$LynxBotPid /tmp/current_linktype.$LynxBotPid /tmp/current_error.$LynxBotPid < "/tmp/lynx_output.$LynxPid" &
+	
+	# open the input fifo on fd 3
+	exec 3<> "/tmp/lynx_cmd_input.$LynxPid"
 
-    # Be sure that lynx is loaded
-    LB_get_current_link > /dev/null
+	# Be sure that lynx is loaded
+	LB_get_current_link > /dev/null
 }
 export -f LB_startlynxbot
 
@@ -50,13 +50,13 @@ LB_Help_get_current_link="LB_get_current_link
 echo: the text of the current link
 return 0"
 function LB_get_current_link {
-    nbla_=$((nbla+1));
-    while ((nbla != nbla_)) ; do
-    	read nbla CurrentLink < /tmp/current_link.$LynxBotPid 
-        "$LynxBotBin"/usleep 3000
-        read nbla_ CurrentLink < /tmp/current_link.$LynxBotPid
-    done
-    echo "$CurrentLink"
+	nbla_=$((nbla+1));
+	while ((nbla != nbla_)) ; do
+		read nbla CurrentLink < /tmp/current_link.$LynxBotPid 
+		"$LynxBotBin"/usleep 3000
+		read nbla_ CurrentLink < /tmp/current_link.$LynxBotPid
+	done
+	echo "$CurrentLink"
 }
 export -f LB_get_current_link
 
@@ -64,13 +64,13 @@ LB_Help_get_current_linktype="LB_get_current_linktype
 echo: the current link type (text)
 return 0"
 function LB_get_current_linktype {
-    nbla_=$((nbla+1));
-    while ((nbla != nbla_)) ; do
-    	read nbla CurrentLinkType < /tmp/current_linktype.$LynxBotPid 
-        "$LynxBotBin"/usleep 3000
-        read nbla_ CurrentLinkType < /tmp/current_linktype.$LynxBotPid
-    done
-    echo "$CurrentLinkType"
+	nbla_=$((nbla+1));
+	while ((nbla != nbla_)) ; do
+		read nbla CurrentLinkType < /tmp/current_linktype.$LynxBotPid 
+		"$LynxBotBin"/usleep 3000
+		read nbla_ CurrentLinkType < /tmp/current_linktype.$LynxBotPid
+	done
+	echo "$CurrentLinkType"
 }
 export -f LB_get_current_linktype
 
@@ -79,20 +79,20 @@ Argument 1: file to store current (lynx) page (default : current_page)
 echo: nothing
 return 0"
 function LB_get_current_page {
-    CurrentPage="${1:-current_page}"
-    [ ! -f "$CurrentPage" ] || rm -f "$CurrentPage" || return 3
-    if LB_get_current_linktype | grep -i "entry field" > /dev/null ; then
-	    echo "key ^V" >&3
-    fi
-    echo "key p" >&3
-    echo "key ^J" >&3
-    echo "key ^U" >&3
-    "$LynxBotBin"/setstrforlynx "$CurrentPage" >&3
-    echo "key ^J" >&3
-    # using fuser is better
-    while ! [ -f "$CurrentPage" ] ; do
-        "$LynxBotBin"/usleep 10000
-    done
+	CurrentPage="${1:-current_page}"
+	[ ! -f "$CurrentPage" ] || rm -f "$CurrentPage" || return 3
+	if LB_get_current_linktype | grep " entry field$" > /dev/null ; then
+		echo "key ^V" >&3
+	fi
+	echo "key p" >&3
+	echo "key ^J" >&3
+	echo "key ^U" >&3
+	"$LynxBotBin"/setstrforlynx "$CurrentPage" >&3
+	echo "key ^J" >&3
+	# using fuser is better
+	while ! [ -f "$CurrentPage" ] ; do
+		"$LynxBotBin"/usleep 10000
+	done
 }
 export -f LB_get_current_page
 
@@ -101,21 +101,21 @@ Argument 1: file to store current source (default : current_source)
 echo: nothing
 return 0"
 function LB_get_current_source {
-    CurrentPage="${1:-current_source}"
-    [ ! -f "$CurrentPage" ] || rm -f "$CurrentPage" || return 3
-    if LB_get_current_linktype | grep -i "entry field" > /dev/null ; then
-	    echo "key ^V" >&3
-    fi
-    echo "key \\" >&3
-    echo "key p" >&3
-    echo "key ^J" >&3
-    echo "key ^U" >&3
-    "$LynxBotBin"/setstrforlynx "$CurrentPage" >&3
-    echo "key ^J" >&3
-    echo "key \\" >&3
-    while ! [ -f "$CurrentPage" ] ; do
-        "$LynxBotBin"/usleep 10000
-    done
+	CurrentPage="${1:-current_source}"
+	[ ! -f "$CurrentPage" ] || rm -f "$CurrentPage" || return 3
+	if LB_get_current_linktype | grep "entry field$" > /dev/null ; then
+		echo "key ^V" >&3
+	fi
+	echo "key \\" >&3
+	echo "key p" >&3
+	echo "key ^J" >&3
+	echo "key ^U" >&3
+	"$LynxBotBin"/setstrforlynx "$CurrentPage" >&3
+	echo "key ^J" >&3
+	echo "key \\" >&3
+	while ! [ -f "$CurrentPage" ] ; do
+		"$LynxBotBin"/usleep 10000
+	done
 }
 export -f LB_get_current_source
 
@@ -124,11 +124,11 @@ Argument 1 = number of link to jump (default : 1)
 echo: nothing
 return 0"
 function LB_go_nextl {
-    for ((if=1;if<=${1:-1};if++)) ; do
-	#echo "key Down Arrow" >&3 #key Up or Down may reach section with no link.
-	echo "key <tab>" >&3
-    done
-#    LB_get_current_link
+	for ((if=1;if<=${1:-1};if++)) ; do
+		#echo "key Down Arrow" >&3 #key Up or Down may reach section with no link.
+		echo "key <tab>" >&3
+	done
+#	LB_get_current_link
 }
 export -f LB_go_nextl
 
@@ -137,11 +137,11 @@ Argument 1 = number of link to jump (default : 1)
 echo: nothing
 return 0"
 function LB_go_previousl {
-    for ((if=1;if<=${1:-1};if++)) ; do
-	#echo "key Up Arrow" >&3 #key Up or Down may reach section with no link.
-	echo "key Back Tab" >&3
-    done
-#    LB_get_current_link
+	for ((if=1;if<=${1:-1};if++)) ; do
+		#echo "key Up Arrow" >&3 #key Up or Down may reach section with no link.
+		echo "key Back Tab" >&3
+	done
+#	LB_get_current_link
 }
 export -f LB_go_previousl
 
@@ -150,9 +150,9 @@ Argument 1: which previous page to reach (default : 1)
 echo: nothing
 return 0"
 function LB_go_previouspage {
-    for ((if=1;if<=${1:-1};if++)) ; do
-	echo "key Left Arrow" >&3
-    done
+	for ((if=1;if<=${1:-1};if++)) ; do
+		echo "key Left Arrow" >&3
+	done
 }
 export -f LB_go_previouspage
 
@@ -160,11 +160,11 @@ LB_Help_secure_go_link="LB_secure_go_link
 echo: nothing
 return 9 if unsure link has been reached, 0 if success."
 function LB_secure_go_link {
-    [ ! -f "/tmp/current_error.$LynxBotPid" ] || rm -f "/tmp/current_error.$LynxBotPid" || return 3
-    echo "key Right Arrow" >&3
-    LB_get_current_page "/tmp/current_page.$LynxBotPid"
-    "$LynxBotBin"/usleep 50000
-    if [ -f "/tmp/current_error.$LynxBotPid" ] ; then return 9 ; fi
+	[ ! -f "/tmp/current_error.$LynxBotPid" ] || rm -f "/tmp/current_error.$LynxBotPid" || return 3
+	echo "key Right Arrow" >&3
+	LB_get_current_page "/tmp/current_page.$LynxBotPid"
+	"$LynxBotBin"/usleep 50000
+	[ -f "/tmp/current_error.$LynxBotPid" ] && return 9
 }
 export -f LB_secure_go_link
 
@@ -172,7 +172,7 @@ LB_Help_go_link="LB_go_link
 echo: nothing
 return 0"
 function LB_go_link {
-    echo "key Right Arrow" >&3
+	echo "key Right Arrow" >&3
 }
 export -f LB_go_link
 
@@ -181,7 +181,7 @@ Jump to the first link of the page.
 echo: nothing
 return 0"
 function LB_go_firstl {
-    echo "key Home" >&3
+	echo "key Home" >&3
 }
 export -f LB_go_firstl
 
@@ -190,7 +190,7 @@ Jump to the last link of the page.
 echo: nothing
 return 0"
 function LB_go_lastl {
-    echo "key End" >&3
+	echo "key End" >&3
 }
 export -f LB_go_lastl
 
@@ -199,32 +199,29 @@ Argument 1: which url to get (mandatory)
 echo: nothing
 return 9 if no given url or unsure that url has been reached, 0 if success."
 function LB_secure_go_to_url {
-    if [ "$1" ] ; then
-		[ ! -f "/tmp/current_error.$LynxBotPid" ] || rm -f "/tmp/current_error.$LynxBotPid" || return 3
-		echo "key g" >&3
-    	"$LynxBotBin"/setstrforlynx "$1" >&3
-    	echo "key ^J" >&3
-        LB_get_current_page "/tmp/current_page.$LynxBotPid"
-        "$LynxBotBin"/usleep 5000
-        if [ -f "/tmp/current_error.$LynxBotPid" ] ; then return 9 ; fi
-    else
-        return 9
-    fi
+	[ "$1" ] || return 9
+
+	[ ! -f "/tmp/current_error.$LynxBotPid" ] || rm -f "/tmp/current_error.$LynxBotPid" || return 3
+	echo "key g" >&3
+	"$LynxBotBin"/setstrforlynx "$1" >&3
+	echo "key ^J" >&3
+	LB_get_current_page "/tmp/current_page.$LynxBotPid"
+	"$LynxBotBin"/usleep 50000
+	[ -f "/tmp/current_error.$LynxBotPid" ] && return 9
 }
 export -f LB_secure_go_to_url
+
 
 LB_Help_go_to_url="LB_go_to_url URL
 Argument 1: which url to get (mandatory)
 echo: nothing
 return 9 if no given url, else 0."
 function LB_go_to_url {
-    if [ "$1" ] ; then
-		echo "key g" >&3
-    	"$LynxBotBin"/setstrforlynx "$1" >&3
-    	echo "key ^J" >&3
-	else
-		return 9
-    fi
+	[ "$1" ] || return 9
+
+	echo "key g" >&3
+	"$LynxBotBin"/setstrforlynx "$1" >&3
+	echo "key ^J" >&3
 }
 export -f LB_go_to_url
 
@@ -232,8 +229,7 @@ LB_Help_refresh_page="LB_refresh_page
 echo: nothing
 return 0."
 function LB_refresh_page {
-# no Argument
-    echo "key ^R" >&3
+	echo "key ^R" >&3
 }
 export -f LB_refresh_page
 
@@ -242,13 +238,11 @@ Argument 1: file to store info on current page and link (default: current_info)
 echo: nothing
 return 0"
 function LB_get_current_info {
-    echo "key =" >&3
-    LB_get_current_page "${1:-current_info}"
-    echo "key =" >&3
+	echo "key =" >&3
+	LB_get_current_page "${1:-current_info}"
+	echo "key =" >&3
 }
 export -f LB_get_current_info
-
-
 
 LB_Help_search_link="LB_search_link PATTERN [max_number]
 Argument 1: which link to search (mandatory)
@@ -256,16 +250,17 @@ Argument 2: max number of links to parse before exiting (default: 64)
 echo: nothing
 return 0 if the link is found, 9 if not."
 function LB_search_link {
-    if ! [ "$1" ] ; then return 9 ; fi
-    isearch=0
-    while ((isearch++<${2:-64})) ; do
-	if echo "$(LB_get_current_link)" | grep "$1" ; then
-	    return 0
-        else
-            LB_go_nextl
-        fi
-    done
-    return 9
+	[ "$1" ] || return 9 
+	isearch=0
+	while ((isearch++<${2:-64})) ; do
+#TODO: (re)move $2 use, and grep "@" instead
+		if echo "$(LB_get_current_link)" | grep "$1" ; then
+			return 0
+		else
+			LB_go_nextl
+		fi
+	done
+	return 9
 }
 export -f LB_search_link
 
@@ -287,27 +282,27 @@ Note: Types use to be: 'Unknow', 'NORMAL LINK', 'Text entry field', 'Password en
 # 7 Option list
 # 8 Choice list
 function LB_search_linktype {
-    if ! [ "$1" ] ; then return 9 ; fi
-    isearch=0
-    while ((isearch++<${2:-64})) ; do
+	[ "$1" ] || return 9
+	isearch=0
+	while ((isearch++<${2:-64})) ; do
 #TODO: (re)move $2 use, and grep "@" instead
-	if echo "$(LB_get_current_linktype)" | grep "$1" > /dev/null ; then
-	    return 0
-	else
-	    LB_go_nextl
-	fi
-    done
-    return 9
+		if LB_get_current_linktype | grep "$1" > /dev/null ; then
+			return 0
+		else
+			LB_go_nextl
+		fi
+	done
+	return 9
 }
 export -f LB_search_linktype
 
 LB_Help_write_string="LB_write_string STRING
 Argument 1: String to write in a Text entry field.
 echo: nothing
-return 9 if current type is not 'Text entry field', 0 if OK."
+return 9 if current type is not ' entry field', 0 if OK."
 function LB_write_string {
-    if ! echo "$(LB_get_current_linktype)" | grep " entry field$" > /dev/null ; then return 9 ; fi
-    "$LynxBotBin"/setstrforlynx "$1" >&3
+	LB_get_current_linktype | grep " entry field$" > /dev/null || return 9
+	"$LynxBotBin"/setstrforlynx "$1" >&3
 }
 export -f LB_write_string
 
@@ -316,13 +311,13 @@ Close the connected lynx and lynxbot.sh session.
 echo: nothing
 return 0."
 function LB_stop {
-    echo "key ^D" >&3
-    rm -f "/tmp/current_link.$LynxBotPid" 
-    rm -f "/tmp/current_linktype.$LynxBotPid"
-    rm -f "/tmp/current_error.$LynxBotPid" 2> /dev/null
-    rm -f "/tmp/current_page.$LynxBotPid" 2> /dev/null
-    rm -f "/tmp/current_bot.$LynxPid"
-    wait
-    exec 3>&-
+	echo "key ^D" >&3
+	rm -f "/tmp/current_link.$LynxBotPid" 
+	rm -f "/tmp/current_linktype.$LynxBotPid"
+	rm -f "/tmp/current_error.$LynxBotPid" 2> /dev/null
+	rm -f "/tmp/current_page.$LynxBotPid" 2> /dev/null
+	rm -f "/tmp/current_bot.$LynxPid"
+	wait
+	exec 3>&-
 }
 export -f LB_stop
